server:
  port: 8888
spring:
  application:
    name: springbootadmin
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization: true
endpoints:
  health:
    sensitive: false