server:
  port: 8055
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/sleepmy/configs.git     # 配置git仓库的地址
          search-paths: music                                    # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 346442030@qq.com                                             # git仓库的账号
          password: *****                                        # git仓库的密码
#  boot:
#    admin:
#      url: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/